### ISSUE TITLE
Inconsistent use of tabs and spaces in indentation. 

### ISSUE THREAD

**Issue by Nereg** [Gramps/SteamworksForPython#49]
Hello! I tried to use your library I pull latest release and copied test code from [here](https://github.com/philippj/SteamworksPy/blob/master/examples/basic/__init__.py). And python told me this error:
```
$ py main.py
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from steamworks import STEAMWORKS # Import main STEAMWORKS class
  File "D:\Projects\Current\SteamworksPy\steamworks\__init__.py", line 28, in <module>
    from steamworks.interfaces.users        import SteamUsers
  File "D:\Projects\Current\SteamworksPy\steamworks\interfaces\users.py", line 52
    """Retrieves an authentication ticket. Immediately usable in AuthenticateUserTicket.
                                                                                       ^
TabError: inconsistent use of tabs and spaces in indentation
```
Also I tried to remove comment in [users.py](https://github.com/philippj/SteamworksPy/blob/master/steamworks/interfaces/users.py) but then this error happened:
```
$ py main.py
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    steamworks = STEAMWORKS()
  File "D:\Projects\Current\SteamworksPy\steamworks\__init__.py", line 50, in __init__
    self._initialize()
  File "D:\Projects\Current\SteamworksPy\steamworks\__init__.py", line 93, in _initialize
    self._load_steamworks_api()
  File "D:\Projects\Current\SteamworksPy\steamworks\__init__.py", line 106, in _load_steamworks_api
    f = getattr(self._cdll, method_name)
  File "C:\Users\Oleg\AppData\Local\Programs\Python\Python38-32\lib\ctypes\__init__.py", line 382, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Oleg\AppData\Local\Programs\Python\Python38-32\lib\ctypes\__init__.py", line 387, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'GetAuthSessionTicket' not found
```
Also new version of steamworks SDK released and I use it not older.
OS: Windows 10 1809 64 bit
Python: `Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)] on win32`
DLL: downloaded [here](https://github.com/philippj/SteamworksPy/releases/tag/v1.6.2) (32-bit version)
Main.py : [here](https://github.com/philippj/SteamworksPy/blob/master/examples/basic/__init__.py)
Is steam running? : yes
File structure: https://prnt.sc/u42d27
P.S. I rewrote method to do the same and it seem that I use outdated version of dll. But I don't know how to compile it to 32-bit.
P.P.S Lol Steam released two new versions while I was working ! Madness !

**Comment by Nereg** [comment]
Hell I hate windows. I tried to build labrary but everytime I got such errors:
```
The input line is too long.
The syntax of the command is incorrect.
```
Even with stock script! Solution was to restart command line ...

**Comment by Gramps** [comment]
That's a weird error.  What was the command it thought was too long?
